import { Orbitron, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${montserrat.variable} antialiased h-full relative`}>
        <div className="container h-full border border-l-amber-800 border-r-amber-500 border-t-transparent border-b-transparent absolute left-1/2 top-0 -translate-x-1/2 -z-10">
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
